### ISSUE TITLE
在vue3的vite脚手架中怎么用呢(how to use in vite)

### ISSUE THREAD

**Issue by cjx19961030** [kensnyder/quill-image-resize-module#140]

**Comment by cjx19961030** [comment]
在vue3的vite脚手架中怎么用呢

**Comment by namegaoyang** [comment]
解决了吗 一样遇到这个问题

**Comment by mcheung610** [comment]
我也是

**Comment by yaoqq632319345** [comment]
```js
const inject = require('@rollup/plugin-inject');

plugins: [,
  inject({
    'window.Quill': ['@vueup/vue-quill', 'Quill']
  })
]
```

**Comment by qikai713** [comment]
> ```js
> const inject = require('@rollup/plugin-inject');
> 
> plugins: [,
>   inject({
>     'window.Quill': ['@vueup/vue-quill', 'Quill']
>   })
> ]
> ```

请问在组件内怎么使用呢 
import {Quill, QuillEditor} from "@vueup/vue-quill";
import { ImageResize } from 'quill-image-resize-module';
Quill.register('modules/imageResize', ImageResize);
不生效

**Comment by qikai713** [comment]
> ```js
> const inject = require('@rollup/plugin-inject');
> 
> plugins: [,
>   inject({
>     'window.Quill': ['@vueup/vue-quill', 'Quill']
>   })
> ]
> ```

请问一下页面怎么使用呢

**Comment by pine-chen** [comment]
因为在import的时候quill没有注册到window上，

在main.js里加入以下代码即可
```js
import { Quill } from 'vue-quill-editor'

window.Quill = Quill
```

**Comment by pine-chen** [comment]
因为在import的时候quill没有注册到window上，

在main.js里加入以下代码即可
```js
import { Quill } from 'vue-quill-editor'

window.Quill = Quill
```
这是我临时的一个解决办法，如果你可以将window.Quill = Quill通过vite注册，希望能分享一下您的写法

**Comment by weiximei** [comment]
需要使用到这个库
```
@rollup/plugin-inject
```

在 Vite 中 plugins 节点下

```
import inject from '@rollup/plugin-inject';
..... 省略一些代码

plugins[
    // ..... 一些其他插件配置
    inject({
      'window.Quill': ['@vueup/vue-quill', 'Quill'],
      Quill: ['@vueup/vue-quill', 'Quill'],
    }),
]
```

然后 Quill 富文本注册插件 ImageDrop 、imageResize
```
  import { QuillEditor, Quill } from '@vueup/vue-quill';
  import '@vueup/vue-quill/dist/vue-quill.snow.css';
  import { ImageDrop } from 'quill-image-drop-module';
  import imageResize from 'quill-image-resize-module';

  Quill.register('modules/ImageDrop', ImageDrop);
  Quill.register('modules/imageResize', imageResize);
```

最后效果

![image](https://user-images.githubusercontent.com/37061242/231824859-a12a0678-64ac-49db-84fd-b89a2a130b47.png)



我已经写在简书上 [VUE3 使用 vue-quill 富文本库、使用图片大小等插件](https://www.jianshu.com/p/76cc55732cff?v=1681403239878)

**Comment by lv23ji** [comment]
打包的时候有报RollupError: "default" is not exported by "node_modules/quill-image-resize-module/image-resize.min.js"吗

**Comment by rizkipadhil** [comment]
这个解决方案已经找到了吗？我在使用上述解决方案构建时仍然遇到错误。"default" 没有被 "node_modules/quill-image-resize-module/image-resize.min.js" 导出。

**Comment by weiximei** [comment]
关于打包，报错 【“default” 不是由 “node_modules/quill-image-resize-module/image-resize.min.js”导出的 】 ，只需要直接导入就可以 (文章里给出了最新代码)
`import 'quill-image-resize-module/image-resize.min.js';`

[VUE3 使用 vue-quill 富文本库、使用图片大小等插件](https://www.jianshu.com/p/76cc55732cff?v=1681403239878)

**Comment by ceuer** [comment]
谢谢，提供实现方案。
我本地开发测试没有问题。
但是打包（npm run build:prod）后运行报错：
Uncaught TypeError: Cannot set properties of undefined (setting 'ImageResize')
    at index-1Az4iJXG.js:113:1452
    at index-1Az4iJXG.js:113:1458
![image](https://github.com/kensnyder/quill-image-resize-module/assets/27793773/4aae9d61-0c46-4b3e-aeec-bf590d47f89d)
请问，有没有遇到这个问题？如何解决呢？谢谢

**Comment by kyrie668** [comment]
> 谢谢，提供实现方案。 我本地开发测试没有问题。 但是打包（npm run build:prod）后运行报错： Uncaught TypeError: Cannot set properties of undefined (setting 'ImageResize') at index-1Az4iJXG.js:113:1452 at index-1Az4iJXG.js:113:1458 ![image](https://private-user-images.githubusercontent.com/27793773/293136312-4aae9d61-0c46-4b3e-aeec-bf590d47f89d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjMwNTQsIm5iZiI6MTcxNTE2Mjc1NCwicGF0aCI6Ii8yNzc5Mzc3My8yOTMxMzYzMTItNGFhZTlkNjEtMGM0Ni00YjNlLWFlZWMtYmY1OTBkNDdmODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDEwMDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTg4NzUxYTVlODY5MTgyOTkwNzc3YzU1ZWNhNjg1Yzc4N2UzMGE3ZTU3ZjQzODY4MTllYzI2NjllOTBlNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7gQ5nyfwCLeeBYE7GOB5rwudr1EZS-Gxnky6APYQHEE) 请问，有没有遇到这个问题？如何解决呢？谢谢

我也遇到这个问题，兄弟你怎么解决的

**Comment by wangrensan** [comment]
@kyrie668 @ceuer 找到原因了吗？

**Comment by Fuphoenixes** [comment]
这么写可以解决
```
const init = async () => {

  window.Quill = Quill;
  const { default: ImageResize } = await import('quill-image-resize-module');
  Quill.register('modules/imageResize', ImageResize);

  const quill = new Quill('#editor', {
     // xxxxx
  });
};
```

**Comment by Q-OldStreet** [comment]
> ```js
> const inject = require('@rollup/plugin-inject');
> 
> plugins: [,
>   inject({
>     'window.Quill': ['@vueup/vue-quill', 'Quill']
>   })
> ]
> ```
不太行呀

**Comment by bigQY** [comment]
> 这么写可以解决
> 
> ```
> const init = async () => {
> 
>   window.Quill = Quill;
>   const { default: ImageResize } = await import('quill-image-resize-module');
>   Quill.register('modules/imageResize', ImageResize);
> 
>   const quill = new Quill('#editor', {
>      // xxxxx
>   });
> };
> ```

这样写确实可以，还能解决这个问题



> 谢谢，提供实现方案。 我本地开发测试没有问题。 但是打包（npm run build:prod）后运行报错： Uncaught TypeError: Cannot set properties of undefined (setting 'ImageResize') at index-1Az4iJXG.js:113:1452 at index-1Az4iJXG.js:113:1458 ![image](https://private-user-images.githubusercontent.com/27793773/293136312-4aae9d61-0c46-4b3e-aeec-bf590d47f89d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTAzMTUsIm5iZiI6MTczMDcxMDAxNSwicGF0aCI6Ii8yNzc5Mzc3My8yOTMxMzYzMTItNGFhZTlkNjEtMGM0Ni00YjNlLWFlZWMtYmY1OTBkNDdmODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA4NDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZGEwYjI3MDliMzM4YWNlNmQ5ZDFkN2NhNWY0ZjhlNmQyMGE1N2FlNzMyZGFmN2ZlMTAxMTYyMmI4NzJiZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mcjvyExF-K-qN4eufeEN3JSxN51NJiLFykAy_m5yzxs) 请问，有没有遇到这个问题？如何解决呢？谢谢

**Comment by persistencess** [comment]
@appsflare/quill-image-resize-module用这个库，其他配置一样就行
