### ISSUE TITLE
I am getting  Cannot read properties of undefined (reading 'imports')

### ISSUE THREAD

**Issue by kaurkaranjeet** [kensnyder/quill-image-resize-module#154]
Hi, I am getting this error on my browser console. I am using Vue2.6. I have installed this version Here is my package.json 
` "quill": "^1.3.7",
    "quill-image-drop-module": "^1.0.3",
    "quill-image-resize-module": "^3.0.0",`
    
 Here is my Home.vue file 
`
import { VueEditor, Quill } from "vue2-editor";
import { ImageDrop } from "quill-image-drop-module";
import ImageResize from "quill-image-resize-module";
Quill.register("modules/imageDrop", ImageDrop);
Quill.register("modules/imageResize", ImageResize);
`

In IDE i am getting `" Could not find a declaration file for module 'quill-image-resize-module'. Try `npm install @types/quill-image-resize-module` if it exists or add a new declaration (.d.ts) file containing `declare module 'quill-image-resize-module';`Vetur(7016) "`

in console i am getting
`
vue-router.esm.js:2316 TypeError: Cannot read properties of undefined (reading 'imports')
    at Object.eval (image-resize.min.js:1:1)
    at e (image-resize.min.js:1:1)
    at Object.eval (image-resize.min.js:1:1)
    at e (image-resize.min.js:1:1)
    at eval (image-resize.min.js:1:1)
    at eval (image-resize.min.js:1:1)
    at eval (image-resize.min.js:1:1)
    at eval (image-resize.min.js:1:1)
    at ./node_modules/quill-image-resize-module/image-resize.min.js (src_views_listYourProperty_ListYourPropBuildListing_vue.js:445:1)
    at __webpack_require__ (app.js:1057:33)
`

**Comment by maykon-oliveira** [comment]
Me too.

**Comment by maks1mp** [comment]
I am facing the same issue. Any ideas?

**Comment by hsalem7** [comment]
I think you are using the latest version of quill while this library supports only the old version.

**Comment by xinyu-yu** [comment]
[that answer](https://github.com/kensnyder/quill-image-resize-module/issues/54#issuecomment-535856666) ，solved my problem
